# Generated by Django 6.0.3 on 2026-04-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_gamesession_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shield_used_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_shields',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('quick_math', 'Quick Math'), ('focus_tap', 'Focus Tap'), ('number_recall', 'Number Recall'), ('color_count_focus', 'Color Count Focus'), ('speed_pattern', 'Speed Pattern'), ('reverse_order', 'Reverse Order'), ('war_mode_skirmish', 'War Mode Skirmish'), ('war_mode_battle', 'War Mode Battle'), ('war_mode_full_war', 'War Mode Full War')], default='quick_math', max_length=20),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='source',
            field=models.CharField(choices=[('task', 'Task'), ('game', 'Game'), ('journal', 'Journal')], max_length=20),
        ),
    ]
