# Generated by Django 6.0.3 on 2026-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_shield_used_today_user_streak_shields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_perfect_week_shield_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
