# Generated by Django 6.0.3 on 2026-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_last_perfect_week_shield_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipped_badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
