# Generated by Django 6.0.3 on 2026-04-06 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_gamesession_game_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("complete_3_tasks", "Complete 3 Tasks"),
                            ("earn_20_xp_from_games", "Earn 20 XP from Games"),
                            ("write_journal_entry", "Write Journal Entry"),
                            ("complete_morning_task_before_10am", "Complete Morning Task Before 10AM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("target_value", models.IntegerField(default=1)),
                ("reward_xp", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyChallengeCompletion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="api.dailychallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_challenge_completions",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "challenge"),
                        name="unique_user_daily_challenge_completion",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="xplog",
            name="source",
            field=models.CharField(
                choices=[
                    ("task", "Task"),
                    ("game", "Game"),
                    ("journal", "Journal"),
                    ("daily_challenge", "Daily Challenge"),
                ],
                max_length=20,
            ),
        ),
    ]
