# Generated by Django 6.0.3 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_coach_user_coach_note_user_is_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachinvite',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
