# Generated by Django 6.0.3 on 2026-07-28 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_workout_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMetricEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metric_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('is_default_weight', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default_weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientMetricSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.metricdefinition')),
            ],
            options={
                'ordering': ['-metric_definition__is_default_weight', 'metric_definition__name'],
            },
        ),
        migrations.CreateModel(
            name='BodyMetricValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.bodymetricentry')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_values', to='api.metricdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='progress_photos/%Y/%m/')),
                ('angle', models.CharField(blank=True, choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back'), ('other', 'Other')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bodymetricentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_body_metric_entry_per_user_date'),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.UniqueConstraint(fields=('coach', 'name'), name='unique_metric_definition_per_coach'),
        ),
        migrations.AddConstraint(
            model_name='clientmetricsubscription',
            constraint=models.UniqueConstraint(fields=('client', 'metric_definition'), name='unique_client_metric_subscription'),
        ),
        migrations.AddConstraint(
            model_name='bodymetricvalue',
            constraint=models.UniqueConstraint(fields=('entry', 'metric_definition'), name='unique_body_metric_value_per_entry_metric'),
        ),
    ]
