from django.urls import path

from .artifact_views import EquipArtifactView, PrestigeView, VaultView

from .views import (
    AssignDailyTasksView,
    AuthMeView,
    ChallengeAcceptView,
    ChallengeCreateView,
    ChallengeDetailView,
    ChallengeListView,
    CompleteTaskView,
    CreateUserTaskView,
    DailyChallengeView,
    DailyTasksView,
    DeleteUserTaskView,
    EquipBadgeView,
    FocusPoolTasksView,
    ForgotPasswordView,
    GameDailyRemainingView,
    GameStartView,
    GameSubmitView,
    HelloView,
    JournalHistoryView,
    JournalView,
    LeaderboardView,
    PrestigeLeaderboardView,
    LoginView,
    ProfileCalendarView,
    ProfileFocusStatsView,
    PushSubscriptionView,
    RefreshTokenView,
    RegisterView,
    ResetPasswordView,
    SeedTasksView,
    UpdateFocusCategoryView,
    UpdateNameView,
    UserView,
    WeeklyWarReportView,
)

urlpatterns = [
    path("hello/", HelloView.as_view(), name="hello"),
    path("challenges/create/", ChallengeCreateView.as_view(), name="challenge-create"),
    path("challenges/<uuid:pk>/", ChallengeDetailView.as_view(), name="challenge-detail"),
    path("challenges/<uuid:pk>/accept/", ChallengeAcceptView.as_view(), name="challenge-accept"),
    path("challenges/", ChallengeListView.as_view(), name="challenge-list"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/forgot-password/", ForgotPasswordView.as_view(), name="auth-forgot-password"),
    path("auth/reset-password/", ResetPasswordView.as_view(), name="auth-reset-password"),
    path("auth/refresh/", RefreshTokenView.as_view(), name="auth-refresh"),
    path("auth/me/", AuthMeView.as_view(), name="auth-me"),
    path("daily-challenge/", DailyChallengeView.as_view(), name="daily-challenge"),
    path("game/remaining/", GameDailyRemainingView.as_view(), name="game-remaining"),
    path("game/start/", GameStartView.as_view(), name="game-start"),
    path("game/submit/", GameSubmitView.as_view(), name="game-submit"),
    path("complete-task/", CompleteTaskView.as_view(), name="complete-task"),
    # ── Task management ──────────────────────────────────────────────────────
    path("tasks/pool/", FocusPoolTasksView.as_view(), name="tasks-pool"),
    path("tasks/create/", CreateUserTaskView.as_view(), name="tasks-create"),
    path("tasks/<uuid:pk>/", DeleteUserTaskView.as_view(), name="tasks-delete"),
    # ─────────────────────────────────────────────────────────────────────────
    path("user/", UserView.as_view(), name="user"),
    path("user/equip-badge/", EquipBadgeView.as_view(), name="equip-badge"),
    path("user/prestige/", PrestigeView.as_view(), name="user-prestige"),
    path("user/vault/", VaultView.as_view(), name="user-vault"),
    path("user/artifact/equip/", EquipArtifactView.as_view(), name="artifact-equip"),
    path("user/update-name/", UpdateNameView.as_view(), name="user-update-name"),
    path("user/update-focus/", UpdateFocusCategoryView.as_view(), name="user-update-focus"),
    path("profile/calendar/", ProfileCalendarView.as_view(), name="profile-calendar"),
    path("profile/focus-stats/", ProfileFocusStatsView.as_view(), name="profile-focus-stats"),
    path("seed-tasks/", SeedTasksView.as_view(), name="seed-tasks"),
    path("assign-daily-tasks/", AssignDailyTasksView.as_view(), name="assign-daily-tasks"),
    path("daily-tasks/", DailyTasksView.as_view(), name="daily-tasks"),
    path("journal/", JournalView.as_view(), name="journal"),
    path("journal/history/", JournalHistoryView.as_view(), name="journal-history"),
    path("leaderboard/", LeaderboardView.as_view(), name="leaderboard"),
    path("leaderboard/prestige/", PrestigeLeaderboardView.as_view(), name="leaderboard-prestige"),
    path("weekly-report/", WeeklyWarReportView.as_view(), name="weekly-report"),
    path("push/subscribe/", PushSubscriptionView.as_view(), name="push-subscribe"),
]
