from django.urls import path

from .artifact_views import EquipArtifactView, PrestigeView, VaultView

from .views import (
    AssignDailyTasksView,
    AuthMeView,
    ChallengeAcceptView,
    ChallengeCreateView,
    ChallengeDetailView,
    ChallengeListView,
    CompleteTaskView,
    CreateUserTaskView,
    DailyChallengeView,
    DailyTasksView,
    DeleteUserTaskView,
    EquipBadgeView,
    FocusPoolTasksView,
    ForgotPasswordView,
    GameDailyRemainingView,
    GameStartView,
    GameSubmitView,
    HelloView,
    JournalHistoryView,
    JournalView,
    LeaderboardView,
    PrestigeLeaderboardView,
    LoginView,
    ProfileCalendarView,
    ProfileFocusStatsView,
    PushSubscriptionView,
    RefreshTokenView,
    RegisterView,
    ResetPasswordView,
    SeedTasksView,
    UpdateFocusCategoryView,
    UpdateNameView,
    UserView,
    WeeklyWarReportView,
    CoachInviteView,
    CoachInviteRegenerateView,
    CoachInvitePreviewView,
    CoachClientListView,
    CoachClientDetailView,
    CoachClientNoteView,
    CoachClientTaskCreateView,
    CoachClientTaskHistoryView,
    # Workout system
    CoachExerciseListView,
    CoachExerciseDetailView,
    CoachProgramListView,
    CoachProgramDetailView,
    CoachProgramDayCreateView,
    CoachProgramDayDetailView,
    CoachProgramDayExerciseCreateView,
    CoachProgramDayExerciseDetailView,
    CoachClientAssignProgramView,
    CoachClientProgramView,
    WorkoutTodayView,
    WorkoutSubmitView,
    WorkoutHistoryView,
    # Body Metrics system
    MetricConfigView,
    BodyMetricEntryView,
    ProgressPhotoListView,
    ProgressPhotoDetailView,
    CoachMetricDefinitionListView,
    CoachClientMetricConfigView,
    CoachClientMetricSubscriptionView,
    CoachClientMetricEntriesView,
    CoachClientMetricPhotosView,
)

urlpatterns = [
    path("hello/", HelloView.as_view(), name="hello"),
    path("challenges/create/", ChallengeCreateView.as_view(), name="challenge-create"),
    path("challenges/<uuid:pk>/", ChallengeDetailView.as_view(), name="challenge-detail"),
    path("challenges/<uuid:pk>/accept/", ChallengeAcceptView.as_view(), name="challenge-accept"),
    path("challenges/", ChallengeListView.as_view(), name="challenge-list"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/forgot-password/", ForgotPasswordView.as_view(), name="auth-forgot-password"),
    path("auth/reset-password/", ResetPasswordView.as_view(), name="auth-reset-password"),
    path("auth/refresh/", RefreshTokenView.as_view(), name="auth-refresh"),
    path("auth/me/", AuthMeView.as_view(), name="auth-me"),
    path("daily-challenge/", DailyChallengeView.as_view(), name="daily-challenge"),
    path("game/remaining/", GameDailyRemainingView.as_view(), name="game-remaining"),
    path("game/start/", GameStartView.as_view(), name="game-start"),
    path("game/submit/", GameSubmitView.as_view(), name="game-submit"),
    path("complete-task/", CompleteTaskView.as_view(), name="complete-task"),
    # ── Task management ──────────────────────────────────────────────────────
    path("tasks/pool/", FocusPoolTasksView.as_view(), name="tasks-pool"),
    path("tasks/create/", CreateUserTaskView.as_view(), name="tasks-create"),
    path("tasks/<uuid:pk>/", DeleteUserTaskView.as_view(), name="tasks-delete"),
    # ─────────────────────────────────────────────────────────────────────────
    path("user/", UserView.as_view(), name="user"),
    path("user/equip-badge/", EquipBadgeView.as_view(), name="equip-badge"),
    path("user/prestige/", PrestigeView.as_view(), name="user-prestige"),
    path("user/vault/", VaultView.as_view(), name="user-vault"),
    path("user/artifact/equip/", EquipArtifactView.as_view(), name="artifact-equip"),
    path("user/update-name/", UpdateNameView.as_view(), name="user-update-name"),
    path("user/update-focus/", UpdateFocusCategoryView.as_view(), name="user-update-focus"),
    path("profile/calendar/", ProfileCalendarView.as_view(), name="profile-calendar"),
    path("profile/focus-stats/", ProfileFocusStatsView.as_view(), name="profile-focus-stats"),
    path("seed-tasks/", SeedTasksView.as_view(), name="seed-tasks"),
    path("assign-daily-tasks/", AssignDailyTasksView.as_view(), name="assign-daily-tasks"),
    path("daily-tasks/", DailyTasksView.as_view(), name="daily-tasks"),
    path("journal/", JournalView.as_view(), name="journal"),
    path("journal/history/", JournalHistoryView.as_view(), name="journal-history"),
    path("leaderboard/", LeaderboardView.as_view(), name="leaderboard"),
    path("leaderboard/prestige/", PrestigeLeaderboardView.as_view(), name="leaderboard-prestige"),
    path("weekly-report/", WeeklyWarReportView.as_view(), name="weekly-report"),
    path("push/subscribe/", PushSubscriptionView.as_view(), name="push-subscribe"),
    # ── Coach endpoints ──
    path("coach/invite/", CoachInviteView.as_view(), name="coach-invite"),
    path("coach/invite/regenerate/", CoachInviteRegenerateView.as_view(), name="coach-invite-regenerate"),
    path("coach/invite/<str:code>/preview/", CoachInvitePreviewView.as_view(), name="coach-invite-preview"),
    path("coach/clients/", CoachClientListView.as_view(), name="coach-clients"),
    path("coach/clients/<uuid:client_id>/", CoachClientDetailView.as_view(), name="coach-client-detail"),
    path("coach/clients/<uuid:client_id>/note/", CoachClientNoteView.as_view(), name="coach-client-note"),
    path("coach/clients/<uuid:client_id>/tasks/", CoachClientTaskCreateView.as_view(), name="coach-client-tasks"),
    path("coach/clients/<uuid:client_id>/tasks/history/", CoachClientTaskHistoryView.as_view(), name="coach-client-tasks-history"),
    # ── Coach Workout / Program Builder ──
    path("coach/exercises/", CoachExerciseListView.as_view(), name="coach-exercises"),
    path("coach/exercises/<uuid:pk>/", CoachExerciseDetailView.as_view(), name="coach-exercise-detail"),
    path("coach/programs/", CoachProgramListView.as_view(), name="coach-programs"),
    path("coach/programs/<uuid:pk>/", CoachProgramDetailView.as_view(), name="coach-program-detail"),
    path("coach/programs/<uuid:pk>/days/", CoachProgramDayCreateView.as_view(), name="coach-program-day-create"),
    path("coach/programs/<uuid:pk>/days/<uuid:day_id>/", CoachProgramDayDetailView.as_view(), name="coach-program-day-detail"),
    path("coach/programs/<uuid:pk>/days/<uuid:day_id>/exercises/", CoachProgramDayExerciseCreateView.as_view(), name="coach-program-day-exercise-create"),
    path("coach/programs/<uuid:pk>/days/<uuid:day_id>/exercises/<uuid:wde_id>/", CoachProgramDayExerciseDetailView.as_view(), name="coach-program-day-exercise-detail"),
    path("coach/clients/<uuid:client_id>/assign-program/", CoachClientAssignProgramView.as_view(), name="coach-client-assign-program"),
    path("coach/clients/<uuid:client_id>/program/", CoachClientProgramView.as_view(), name="coach-client-program"),
    # ── Client Workout ──
    path("workout/today/", WorkoutTodayView.as_view(), name="workout-today"),
    path("workout/submit/", WorkoutSubmitView.as_view(), name="workout-submit"),
    path("workout/history/", WorkoutHistoryView.as_view(), name="workout-history"),
    # ── Client Body Metrics ──
    path("metrics/config/", MetricConfigView.as_view(), name="metric-config"),
    path("metrics/entries/", BodyMetricEntryView.as_view(), name="metric-entries"),
    path("metrics/photos/", ProgressPhotoListView.as_view(), name="metric-photos"),
    path("metrics/photos/<uuid:pk>/", ProgressPhotoDetailView.as_view(), name="metric-photo-detail"),
    # ── Coach Body Metrics ──
    path("coach/metric-definitions/", CoachMetricDefinitionListView.as_view(), name="coach-metric-definitions"),
    path("coach/clients/<uuid:client_id>/metrics/config/", CoachClientMetricConfigView.as_view(), name="coach-client-metric-config"),
    path("coach/clients/<uuid:client_id>/metrics/subscriptions/", CoachClientMetricSubscriptionView.as_view(), name="coach-client-metric-subscriptions"),
    path("coach/clients/<uuid:client_id>/metrics/entries/", CoachClientMetricEntriesView.as_view(), name="coach-client-metric-entries"),
    path("coach/clients/<uuid:client_id>/metrics/photos/", CoachClientMetricPhotosView.as_view(), name="coach-client-metric-photos"),
]

